package com.dhcc.bussiness.sxydidc.alarm.models;

// Generated 2016-11-1 10:20:58 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AlarmNoticeType generated by hbm2java
 */
public class AlarmNoticeType implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AlarmNoticeType [noticeTypeId=" + noticeTypeId + ", name="
				+ name + "]";
	}

	private BigDecimal noticeTypeId;
	private String name;
	private Set<AlarmRule> alarmRules = new HashSet<AlarmRule>(0);

	public AlarmNoticeType() {
	}

	public AlarmNoticeType(BigDecimal noticeTypeId) {
		this.noticeTypeId = noticeTypeId;
	}

	public AlarmNoticeType(BigDecimal noticeTypeId, String name,
			Set<AlarmRule> alarmRules) {
		this.noticeTypeId = noticeTypeId;
		this.name = name;
		this.alarmRules = alarmRules;
	}

	public BigDecimal getNoticeTypeId() {
		return this.noticeTypeId;
	}

	public void setNoticeTypeId(BigDecimal noticeTypeId) {
		this.noticeTypeId = noticeTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<AlarmRule> getAlarmRules() {
		return this.alarmRules;
	}

	public void setAlarmRules(Set<AlarmRule> alarmRules) {
		this.alarmRules = alarmRules;
	}

}
