package com.dhcc.bussiness.sxydidc.alarm.models;

// Generated 2016-11-1 10:20:58 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AlarmRuleValueType generated by hbm2java
 */
public class AlarmRuleValueType implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AlarmRuleValueType [valueTypeId=" + valueTypeId + ", name="
				+ name + ", valueCount=" + valueCount + ", doneWithClass="
				+ doneWithClass + "]";
	}

	private BigDecimal valueTypeId;
	private String name;
	private BigDecimal valueCount;
	private String doneWithClass;
	private Set<AlarmRule> alarmRules = new HashSet<AlarmRule>(0);

	public AlarmRuleValueType() {
	}

	public AlarmRuleValueType(BigDecimal valueTypeId, String name,
			BigDecimal valueCount) {
		this.valueTypeId = valueTypeId;
		this.name = name;
		this.valueCount = valueCount;
	}

	public AlarmRuleValueType(BigDecimal valueTypeId, String name,
			BigDecimal valueCount, String doneWithClass,
			Set<AlarmRule> alarmRules) {
		this.valueTypeId = valueTypeId;
		this.name = name;
		this.valueCount = valueCount;
		this.doneWithClass = doneWithClass;
		this.alarmRules = alarmRules;
	}

	public BigDecimal getValueTypeId() {
		return this.valueTypeId;
	}

	public void setValueTypeId(BigDecimal valueTypeId) {
		this.valueTypeId = valueTypeId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getValueCount() {
		return this.valueCount;
	}

	public void setValueCount(BigDecimal valueCount) {
		this.valueCount = valueCount;
	}

	public String getDoneWithClass() {
		return this.doneWithClass;
	}

	public void setDoneWithClass(String doneWithClass) {
		this.doneWithClass = doneWithClass;
	}

	public Set<AlarmRule> getAlarmRules() {
		return this.alarmRules;
	}

	public void setAlarmRules(Set<AlarmRule> alarmRules) {
		this.alarmRules = alarmRules;
	}

}
