package com.dhcc.bussiness.sxydidc.alarm.models;

// Generated 2016-11-1 10:20:58 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AlarmSeverity generated by hbm2java
 */
public class AlarmSeverity implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AlarmSeverity [severityId=" + severityId + ", name=" + name
				+ ", color=" + color + "]";
	}

	private BigDecimal severityId;
	private String name;
	private String color;
	private Set<AlarmRule> alarmRules = new HashSet<AlarmRule>(0);

	public AlarmSeverity() {
	}

	public AlarmSeverity(BigDecimal severityId, String name) {
		this.severityId = severityId;
		this.name = name;
	}

	public AlarmSeverity(BigDecimal severityId, String name, String color,
			Set<AlarmRule> alarmRules) {
		this.severityId = severityId;
		this.name = name;
		this.color = color;
		this.alarmRules = alarmRules;
	}

	public BigDecimal getSeverityId() {
		return this.severityId;
	}

	public void setSeverityId(BigDecimal severityId) {
		this.severityId = severityId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Set<AlarmRule> getAlarmRules() {
		return this.alarmRules;
	}

	public void setAlarmRules(Set<AlarmRule> alarmRules) {
		this.alarmRules = alarmRules;
	}

}
