package com.dhcc.bussiness.sxydidc.customer95.models;

// Generated 2016-11-9 16:51:52 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contract generated by hbm2java
 */
public class Contract implements java.io.Serializable {

	private String contractId;
	private Customer customer;
	private Double contractMoney;
	private Double discount;
	private Double trafficUnitPrice;
	private Double lowestBandwidth;
	private Date startTime;
	private BigDecimal contractPeriod;
	private String trafficChargeRule;
	private Set<Product> products = new HashSet<Product>(0);

	public void addProduct(Product product){
		product.setContract(this);
		this.products.add(product);
	}
	public Contract() {
	}

	public Contract(String contractId) {
		this.contractId = contractId;
	}

	public Contract(String contractId, Customer customer, Double contractMoney,
			Double discount, Double trafficUnitPrice, Double lowestBandwidth,
			Date startTime, BigDecimal contractPeriod,
			String trafficChargeRule, Set<Product> products) {
		this.contractId = contractId;
		this.customer = customer;
		this.contractMoney = contractMoney;
		this.discount = discount;
		this.trafficUnitPrice = trafficUnitPrice;
		this.lowestBandwidth = lowestBandwidth;
		this.startTime = startTime;
		this.contractPeriod = contractPeriod;
		this.trafficChargeRule = trafficChargeRule;
		this.products = products;
	}

	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Double getContractMoney() {
		return this.contractMoney;
	}

	public void setContractMoney(Double contractMoney) {
		this.contractMoney = contractMoney;
	}

	public Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(Double discount) {
		this.discount = discount;
	}

	public Double getTrafficUnitPrice() {
		return this.trafficUnitPrice;
	}

	public void setTrafficUnitPrice(Double trafficUnitPrice) {
		this.trafficUnitPrice = trafficUnitPrice;
	}

	public Double getLowestBandwidth() {
		return this.lowestBandwidth;
	}

	public void setLowestBandwidth(Double lowestBandwidth) {
		this.lowestBandwidth = lowestBandwidth;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public BigDecimal getContractPeriod() {
		return this.contractPeriod;
	}

	public void setContractPeriod(BigDecimal contractPeriod) {
		this.contractPeriod = contractPeriod;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((contractId == null) ? 0 : contractId.hashCode());
		return result;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Contract other = (Contract) obj;
		if (contractId == null) {
			if (other.contractId != null)
				return false;
		} else if (!contractId.equals(other.contractId))
			return false;
		return true;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Contract [contractId=" + contractId + ", contractMoney="
				+ contractMoney + ", discount=" + discount
				+ ", trafficUnitPrice=" + trafficUnitPrice
				+ ", lowestBandwidth=" + lowestBandwidth + ", startTime="
				+ startTime + ", contractPeriod=" + contractPeriod
				+ ", trafficChargeRule=" + trafficChargeRule + ", products="
				+ products + "]";
	}
	public String getTrafficChargeRule() {
		return this.trafficChargeRule;
	}

	public void setTrafficChargeRule(String trafficChargeRule) {
		this.trafficChargeRule = trafficChargeRule;
	}

	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
