package com.dhcc.bussiness.sxydidc.customer95.models;

// Generated 2016-11-9 16:51:52 by Hibernate Tools 4.3.1

/**
 * ProductIp generated by hbm2java
 */
public class ProductIp implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductIp other = (ProductIp) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ProductIp [id=" + id + "]";
	}

	private ProductIpId id;
	private Product product;

	public ProductIp() {
	}

	public ProductIp(ProductIpId id, Product product) {
		this.id = id;
		this.product = product;
	}

	public ProductIpId getId() {
		return this.id;
	}

	public void setId(ProductIpId id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

}
