package com.dhcc.bussiness.sxydidc.customer95.config.models;

// Generated 2016-12-23 13:03:10 by Hibernate Tools 4.3.1

/**
 * DeviceInterface generated by hbm2java
 */
public class DeviceInterface implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "DeviceInterface [id=" + id + ", nodeId=" + nodeId
				+ ", ifIndex=" + ifIndex + ", ifDesc=" + ifDesc + "]";
	}

	private long id;
	private String nodeId;
	private String ifIndex;
	private String ifDesc;

	public DeviceInterface() {
	}

	public DeviceInterface(long id) {
		this.id = id;
	}

	public DeviceInterface(long id, String nodeId, String ifIndex, String ifDesc) {
		this.id = id;
		this.nodeId = nodeId;
		this.ifIndex = ifIndex;
		this.ifDesc = ifDesc;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(String nodeId) {
		this.nodeId = nodeId;
	}

	public String getIfIndex() {
		return this.ifIndex;
	}

	public void setIfIndex(String ifIndex) {
		this.ifIndex = ifIndex;
	}

	public String getIfDesc() {
		return this.ifDesc;
	}

	public void setIfDesc(String ifDesc) {
		this.ifDesc = ifDesc;
	}

}
