package com.dhcc.bussiness.sxydidc.alarm.models;

// Generated 2016-11-1 10:20:58 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * AlarmInfo generated by hbm2java
 */
public class AlarmInfo implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AlarmInfo [alarmId=" + alarmId + ", ip=" + ip + ", name="
				+ name + ", description=" + description + ", time=" + time
				+ ", severityName=" + severityName + ", severityColor="
				+ severityColor + "]";
	}

	private String alarmId;
	private String ip;
	private String name;
	private String description;
	private Date time;
	private String severityName;
	private String severityColor;

	public AlarmInfo() {
	}

	public AlarmInfo(String alarmId, String ip, String name,
			String description, String severityName, String severityColor) {
		this.alarmId = alarmId;
		this.ip = ip;
		this.name = name;
		this.description = description;
		this.severityName = severityName;
		this.severityColor = severityColor;
	}

	public AlarmInfo(String alarmId, String ip, String name,
			String description, Date time, String severityName,
			String severityColor) {
		this.alarmId = alarmId;
		this.ip = ip;
		this.name = name;
		this.description = description;
		this.time = time;
		this.severityName = severityName;
		this.severityColor = severityColor;
	}

	public String getAlarmId() {
		return this.alarmId;
	}

	public void setAlarmId(String alarmId) {
		this.alarmId = alarmId;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getSeverityName() {
		return this.severityName;
	}

	public void setSeverityName(String severityName) {
		this.severityName = severityName;
	}

	public String getSeverityColor() {
		return this.severityColor;
	}

	public void setSeverityColor(String severityColor) {
		this.severityColor = severityColor;
	}

}
