package com.dhcc.bussiness.sxydidc.alarm.models;

// Generated 2016-11-1 10:20:58 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tsuser generated by hbm2java
 */
public class Tsuser implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Tsuser [id=" + id + ", username=" + username + ", loginname="
				+ loginname + ", userpass=" + userpass + ", sex=" + sex
				+ ", birth=" + birth + ", emailpublic=" + emailpublic
				+ ", emailprivate=" + emailprivate + ", mobilepublic="
				+ mobilepublic + ", mobileprivate=" + mobileprivate
				+ ", phonepublic=" + phonepublic + ", phoneprivate="
				+ phoneprivate + ", area=" + area + ", dcid=" + dcid
				+ ", topcorpid=" + topcorpid + ", remark=" + remark + "]";
	}

	private String id;
	private String username;
	private String loginname;
	private String userpass;
	private String sex;
	private BigDecimal birth;
	private String emailpublic;
	private String emailprivate;
	private String mobilepublic;
	private String mobileprivate;
	private String phonepublic;
	private String phoneprivate;
	private String area;
	private String dcid;
	private String topcorpid;
	private String remark;
	private Set<AlarmRule> alarmRules = new HashSet<AlarmRule>(0);

	public Tsuser() {
	}

	public Tsuser(String id) {
		this.id = id;
	}

	public Tsuser(String id, String username, String loginname,
			String userpass, String sex, BigDecimal birth, String emailpublic,
			String emailprivate, String mobilepublic, String mobileprivate,
			String phonepublic, String phoneprivate, String area, String dcid,
			String topcorpid, String remark, Set<AlarmRule> alarmRules) {
		this.id = id;
		this.username = username;
		this.loginname = loginname;
		this.userpass = userpass;
		this.sex = sex;
		this.birth = birth;
		this.emailpublic = emailpublic;
		this.emailprivate = emailprivate;
		this.mobilepublic = mobilepublic;
		this.mobileprivate = mobileprivate;
		this.phonepublic = phonepublic;
		this.phoneprivate = phoneprivate;
		this.area = area;
		this.dcid = dcid;
		this.topcorpid = topcorpid;
		this.remark = remark;
		this.alarmRules = alarmRules;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getUserpass() {
		return this.userpass;
	}

	public void setUserpass(String userpass) {
		this.userpass = userpass;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public BigDecimal getBirth() {
		return this.birth;
	}

	public void setBirth(BigDecimal birth) {
		this.birth = birth;
	}

	public String getEmailpublic() {
		return this.emailpublic;
	}

	public void setEmailpublic(String emailpublic) {
		this.emailpublic = emailpublic;
	}

	public String getEmailprivate() {
		return this.emailprivate;
	}

	public void setEmailprivate(String emailprivate) {
		this.emailprivate = emailprivate;
	}

	public String getMobilepublic() {
		return this.mobilepublic;
	}

	public void setMobilepublic(String mobilepublic) {
		this.mobilepublic = mobilepublic;
	}

	public String getMobileprivate() {
		return this.mobileprivate;
	}

	public void setMobileprivate(String mobileprivate) {
		this.mobileprivate = mobileprivate;
	}

	public String getPhonepublic() {
		return this.phonepublic;
	}

	public void setPhonepublic(String phonepublic) {
		this.phonepublic = phonepublic;
	}

	public String getPhoneprivate() {
		return this.phoneprivate;
	}

	public void setPhoneprivate(String phoneprivate) {
		this.phoneprivate = phoneprivate;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getDcid() {
		return this.dcid;
	}

	public void setDcid(String dcid) {
		this.dcid = dcid;
	}

	public String getTopcorpid() {
		return this.topcorpid;
	}

	public void setTopcorpid(String topcorpid) {
		this.topcorpid = topcorpid;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<AlarmRule> getAlarmRules() {
		return this.alarmRules;
	}

	public void setAlarmRules(Set<AlarmRule> alarmRules) {
		this.alarmRules = alarmRules;
	}

}
