package com.dhcc.bussiness.sxydidc.customer95.models;

// Generated 2016-11-9 16:51:52 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private String productId;
	private Contract contract;
	private String productName;
	private String productCharacter;
	private BigDecimal productCount;
	private Double productUnitPrice;
	private Double settingBandwidth;
	private String settingBandwidthUnit;
	private String isCharge;
	private Set<ProductIp> productIps = new HashSet<ProductIp>(0);

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((productId == null) ? 0 : productId.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Product other = (Product) obj;
		if (productId == null) {
			if (other.productId != null)
				return false;
		} else if (!productId.equals(other.productId))
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Product [productId=" + productId + ", productName="
				+ productName + ", productCharacter=" + productCharacter
				+ ", productCount=" + productCount + ", productUnitPrice="
				+ productUnitPrice + ", settingBandwidth=" + settingBandwidth
				+ ", settingBandwidthUnit=" + settingBandwidthUnit
				+ ", isCharge=" + isCharge + ", productIps=" + productIps + "]";
	}

	public void addProductIp(ProductIp productIp){
		this.productIps.add(productIp);
	}
	
	public void addProductIp(String ip){
		ProductIp productIp = new ProductIp(new ProductIpId(this.productId,ip),this);
		this.productIps.add(productIp);
	}
	public Product() {
	}

	public Product(String productId) {
		this.productId = productId;
	}

	public Product(String productId, Contract contract, String productName,
			String productCharacter, BigDecimal productCount,
			Double productUnitPrice, Double settingBandwidth,
			String settingBandwidthUnit, String isCharge,
			Set<ProductIp> productIps) {
		this.productId = productId;
		this.contract = contract;
		this.productName = productName;
		this.productCharacter = productCharacter;
		this.productCount = productCount;
		this.productUnitPrice = productUnitPrice;
		this.settingBandwidth = settingBandwidth;
		this.settingBandwidthUnit = settingBandwidthUnit;
		this.isCharge = isCharge;
		this.productIps = productIps;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public Contract getContract() {
		return this.contract;
	}

	public void setContract(Contract contract) {
		this.contract = contract;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductCharacter() {
		return this.productCharacter;
	}

	public void setProductCharacter(String productCharacter) {
		this.productCharacter = productCharacter;
	}

	public BigDecimal getProductCount() {
		return this.productCount;
	}

	public void setProductCount(BigDecimal productCount) {
		this.productCount = productCount;
	}

	public Double getProductUnitPrice() {
		return this.productUnitPrice;
	}

	public void setProductUnitPrice(Double productUnitPrice) {
		this.productUnitPrice = productUnitPrice;
	}

	public Double getSettingBandwidth() {
		return this.settingBandwidth;
	}

	public void setSettingBandwidth(Double settingBandwidth) {
		this.settingBandwidth = settingBandwidth;
	}

	public String getSettingBandwidthUnit() {
		return this.settingBandwidthUnit;
	}

	public void setSettingBandwidthUnit(String settingBandwidthUnit) {
		this.settingBandwidthUnit = settingBandwidthUnit;
	}

	public String getIsCharge() {
		return this.isCharge;
	}

	public void setIsCharge(String isCharge) {
		this.isCharge = isCharge;
	}

	public Set<ProductIp> getProductIps() {
		return this.productIps;
	}

	public void setProductIps(Set<ProductIp> productIps) {
		this.productIps = productIps;
	}

}
