package com.dhcc.bussiness.sxydidc.customer95.models;

// Generated 2016-11-9 16:51:52 by Hibernate Tools 4.3.1

/**
 * ProductIpId generated by hbm2java
 */
public class ProductIpId implements java.io.Serializable {

	private String productId;
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "ProductIpId [productId=" + productId + ", ip=" + ip + "]";
	}

	private String ip;

	public ProductIpId() {
	}

	public ProductIpId(String productId, String ip) {
		this.productId = productId;
		this.ip = ip;
	}

	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductIpId))
			return false;
		ProductIpId castOther = (ProductIpId) other;

		return ((this.getProductId() == castOther.getProductId()) || (this
				.getProductId() != null && castOther.getProductId() != null && this
				.getProductId().equals(castOther.getProductId())))
				&& ((this.getIp() == castOther.getIp()) || (this.getIp() != null
						&& castOther.getIp() != null && this.getIp().equals(
						castOther.getIp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getProductId() == null ? 0 : this.getProductId().hashCode());
		result = 37 * result + (getIp() == null ? 0 : this.getIp().hashCode());
		return result;
	}

}
