package com.dhcc.flow.report.models;

import java.util.Map;

// Generated 2016-12-7 10:58:49 by Hibernate Tools 4.3.1

/**
 * FlowAccount generated by hbm2java
 */
public class FlowAccount implements java.io.Serializable,Exportable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "FlowAccount [id=" + id + "]";
	}

	private FlowAccountId id;

	public FlowAccount() {
	}

	public FlowAccount(FlowAccountId id) {
		this.id = id;
	}

	public FlowAccountId getId() {
		return this.id;
	}

	public void setId(FlowAccountId id) {
		this.id = id;
	}

	public Map<String, Object> convert() {
		// TODO Auto-generated method stub
		return null;
	}

}
