package com.dhcc.flow.report.models;

// Generated 2016-12-7 10:58:49 by Hibernate Tools 4.3.1

/**
 * FlowAccountId generated by hbm2java
 */
public class FlowAccountId implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "FlowAccountId [customerId=" + customerId + ", datetime="
				+ datetime + ", totalcount=" + totalcount + ", flowcount="
				+ flowcount + ", utilhdx=" + utilhdx + ", cabinet=" + cabinet
				+ "]";
	}

	private String customerId;
	private String datetime;
	private String totalcount;
	private String flowcount;
	private String utilhdx;
	private String cabinet;

	public FlowAccountId() {
	}

	public FlowAccountId(String customerId, String datetime, String totalcount,
			String flowcount, String utilhdx, String cabinet) {
		this.customerId = customerId;
		this.datetime = datetime;
		this.totalcount = totalcount;
		this.flowcount = flowcount;
		this.utilhdx = utilhdx;
		this.cabinet = cabinet;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getDatetime() {
		return this.datetime;
	}

	public void setDatetime(String datetime) {
		this.datetime = datetime;
	}

	public String getTotalcount() {
		return this.totalcount;
	}

	public void setTotalcount(String totalcount) {
		this.totalcount = totalcount;
	}

	public String getFlowcount() {
		return this.flowcount;
	}

	public void setFlowcount(String flowcount) {
		this.flowcount = flowcount;
	}

	public String getUtilhdx() {
		return this.utilhdx;
	}

	public void setUtilhdx(String utilhdx) {
		this.utilhdx = utilhdx;
	}

	public String getCabinet() {
		return this.cabinet;
	}

	public void setCabinet(String cabinet) {
		this.cabinet = cabinet== null||"null".equals(cabinet)?"未知":cabinet;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlowAccountId))
			return false;
		FlowAccountId castOther = (FlowAccountId) other;

		return ((this.getCustomerId() == castOther.getCustomerId()) || (this
				.getCustomerId() != null && castOther.getCustomerId() != null && this
				.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getDatetime() == castOther.getDatetime()) || (this
						.getDatetime() != null
						&& castOther.getDatetime() != null && this
						.getDatetime().equals(castOther.getDatetime())))
				&& ((this.getTotalcount() == castOther.getTotalcount()) || (this
						.getTotalcount() != null
						&& castOther.getTotalcount() != null && this
						.getTotalcount().equals(castOther.getTotalcount())))
				&& ((this.getFlowcount() == castOther.getFlowcount()) || (this
						.getFlowcount() != null
						&& castOther.getFlowcount() != null && this
						.getFlowcount().equals(castOther.getFlowcount())))
				&& ((this.getUtilhdx() == castOther.getUtilhdx()) || (this
						.getUtilhdx() != null && castOther.getUtilhdx() != null && this
						.getUtilhdx().equals(castOther.getUtilhdx())))
				&& ((this.getCabinet() == castOther.getCabinet()) || (this
						.getCabinet() != null && castOther.getCabinet() != null && this
						.getCabinet().equals(castOther.getCabinet())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCustomerId() == null ? 0 : this.getCustomerId()
						.hashCode());
		result = 37 * result
				+ (getDatetime() == null ? 0 : this.getDatetime().hashCode());
		result = 37
				* result
				+ (getTotalcount() == null ? 0 : this.getTotalcount()
						.hashCode());
		result = 37 * result
				+ (getFlowcount() == null ? 0 : this.getFlowcount().hashCode());
		result = 37 * result
				+ (getUtilhdx() == null ? 0 : this.getUtilhdx().hashCode());
		result = 37 * result
				+ (getCabinet() == null ? 0 : this.getCabinet().hashCode());
		return result;
	}

}
