package com.dhcc.bussiness.sxydidc.quality.models;

// Generated 2016-11-18 9:47:54 by Hibernate Tools 4.3.1

/**
 * TopoHostNode generated by hbm2java
 */
public class TopoHostNode implements java.io.Serializable {

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "TopoHostNode [id=" + id + ", ipAddress=" + ipAddress
				+ ", ipLong=" + ipLong + ", sysName=" + sysName + ", alias="
				+ alias + ", netMask=" + netMask + ", sysDescr=" + sysDescr
				+ ", sysOid=" + sysOid + ", community=" + community
				+ ", category=" + category + ", managed=" + managed
				+ ", status=" + status + ", discoverstatus=" + discoverstatus
				+ ", sysLocation=" + sysLocation + ", sysContact=" + sysContact
				+ ", snmpversion=" + snmpversion + "]";
	}

	private int id;
	private String ipAddress;
	private String ipLong;
	private String sysName;
	private String alias;
	private String netMask;
	private String sysDescr;
	private String sysOid;
	private String community;
	private Short category;
	private Boolean managed;
	private Short status;
	private Short discoverstatus;
	private String sysLocation;
	private String sysContact;
	private Short snmpversion;

	public TopoHostNode() {
	}

	public TopoHostNode(int id) {
		this.id = id;
	}

	public TopoHostNode(int id, String ipAddress, String ipLong,
			String sysName, String alias, String netMask, String sysDescr,
			String sysOid, String community, Short category, Boolean managed,
			Short status, Short discoverstatus, String sysLocation,
			String sysContact, Short snmpversion) {
		this.id = id;
		this.ipAddress = ipAddress;
		this.ipLong = ipLong;
		this.sysName = sysName;
		this.alias = alias;
		this.netMask = netMask;
		this.sysDescr = sysDescr;
		this.sysOid = sysOid;
		this.community = community;
		this.category = category;
		this.managed = managed;
		this.status = status;
		this.discoverstatus = discoverstatus;
		this.sysLocation = sysLocation;
		this.sysContact = sysContact;
		this.snmpversion = snmpversion;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	public String getIpLong() {
		return this.ipLong;
	}

	public void setIpLong(String ipLong) {
		this.ipLong = ipLong;
	}

	public String getSysName() {
		return this.sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getNetMask() {
		return this.netMask;
	}

	public void setNetMask(String netMask) {
		this.netMask = netMask;
	}

	public String getSysDescr() {
		return this.sysDescr;
	}

	public void setSysDescr(String sysDescr) {
		this.sysDescr = sysDescr;
	}

	public String getSysOid() {
		return this.sysOid;
	}

	public void setSysOid(String sysOid) {
		this.sysOid = sysOid;
	}

	public String getCommunity() {
		return this.community;
	}

	public void setCommunity(String community) {
		this.community = community;
	}

	public Short getCategory() {
		return this.category;
	}

	public void setCategory(Short category) {
		this.category = category;
	}

	public Boolean getManaged() {
		return this.managed;
	}

	public void setManaged(Boolean managed) {
		this.managed = managed;
	}

	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}

	public Short getDiscoverstatus() {
		return this.discoverstatus;
	}

	public void setDiscoverstatus(Short discoverstatus) {
		this.discoverstatus = discoverstatus;
	}

	public String getSysLocation() {
		return this.sysLocation;
	}

	public void setSysLocation(String sysLocation) {
		this.sysLocation = sysLocation;
	}

	public String getSysContact() {
		return this.sysContact;
	}

	public void setSysContact(String sysContact) {
		this.sysContact = sysContact;
	}

	public Short getSnmpversion() {
		return this.snmpversion;
	}

	public void setSnmpversion(Short snmpversion) {
		this.snmpversion = snmpversion;
	}

}
